import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const recoleta = localFont(
    {
      src: [{
        path:"../../public/fonts/recoleta-regulardemo.ttf",
      }],
        variable: "--font-recoleta"
    }
)

const SFProTextRegular = localFont(
    {
        src: [{
            path:"../../public/fonts/SF-Pro-Text-Regular.ttf",
        }]
    }
)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${recoleta.variable}`}>
      <body className={SFProTextRegular.className}>{children}</body>
    </html>
  );
}
